#!/bin/bash
DIR_THIS=$(dirname $0)
cd $DIR_THIS/..
. $DIR_THIS/exportandroid
./cmake_android.sh build/android -DANDROID_ABI="arm64-v8a" -DANDROID_TOOLCHAIN_NAME="aarch64-linux-android-clang" -DURHO3D_SAMPLES=1
